### ISSUE TITLE
Call to undefined function password_verify()

### ISSUE THREAD

**Issue by mudris** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#1]
After fresh install have PHP error 
PHP Fatal error:  Call to undefined function password_verify() in.... cias_helper.php on line 46

**Comment by kishor10d** [comment]
Please check your php version.
To work ```password_verify()```, you need (PHP 5 >= 5.5.0, PHP 7).

Documentation : http://php.net/manual/en/function.password-verify.php

**Comment by priti321** [comment]
I also having same problem.
previously i have php version 5.4. i'm changed it to 5.6.
but when we enter correct login details it also shows mismatch error.

**Comment by kishor10d** [comment]
Can you please update the comment with error?

If your database don't have such password then please first generate the password using following script. Then, paste that password to your password field in user table.

```
<?php
if(!function_exists('getHashedPassword'))
{
    function getHashedPassword($plainPassword)
    {
        return password_hash($plainPassword, PASSWORD_DEFAULT);
    }
}
echo getHashedPassword("codeinsect");
?>
```
You will get hashed password of _codeinsect_. Paste that into the user table and try to login with your email and password - _codeinsect_

**Comment by sibbu2005** [comment]
yo :)

**Comment by ghost** [comment]
hello, I am trying to modifying the code in such way that a user can register himself in the system.. I have made a link just after forgot password and created a corresponding method in the controller class..however it is showing me the following error:
Message: call_user_func_array() expects parameter 1 to be a valid callback, class 'Error' does not have a method 'index'

Filename: core/CodeIgniter.php

Line Number: 532

Backtrace:

File: C:\xampp\htdocs\DUSPORTS2\DUSPORTS\DUSPORTS\index.php
Line: 315
Function: require_once

**Comment by GetItBac92** [comment]
hello, I am trying to modifying the code in such way that a user can register himself in the system.. I have made a link just after forgot password and created a corresponding method in the controller class..however it is showing me the following error:
Message: call_user_func_array() expects parameter 1 to be a valid callback, class 'Error' does not have a method 'index'

Filename: core/CodeIgniter.php

Line Number: 532

Backtrace:

File: C:\xampp\htdocs\DUSPORTS2\DUSPORTS\DUSPORTS\index.php
Line: 315
Function: require_once

**Comment by AZtanveer1997** [comment]
Error Number: 1054

Unknown column 'BaseTbl.isAdmin' in 'field list'

SELECT `BaseTbl`.`userId`, `BaseTbl`.`password`, `BaseTbl`.`name`, `BaseTbl`.`roleId`, `BaseTbl`.`isAdmin`, `Roles`.`role` FROM `tbl_users` as `BaseTbl` JOIN `tbl_roles` as `Roles` ON `Roles`.`roleId` = `BaseTbl`.`roleId` WHERE `BaseTbl`.`email` = 'aztanveer1997@gmail.com' AND `BaseTbl`.`isDeleted` = 0
