### ISSUE TITLE
I get the following error

### ISSUE THREAD

**Issue by ghost** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#10]
The requested URL /cias/loginMe was not found on this server.

**Comment by kishor10d** [comment]
please check your directory structure. I make it for root folder as ```cias```.

**Comment by ghost** [comment]
Moved all the files to document root. And still have the same error.

**Comment by kishor10d** [comment]
You need to change the routes as per requirement. Can you provide your directory structure from document root folder?

**Comment by ghost** [comment]
I am new to CodeIgniter and CIAS. could you let me know where to change the routes. I am using cias as the document route. In Ubuntu the folder is /var/www/html/cias

**Comment by ghost** [comment]
Checked through the Application/config/route.php and checked the route settings the loginMe is set to login/loginMe. I understand that login.php controller has the funtion loginMe, which is correct. Just wondering why it is not pointing correct. Is there something I am missing.

**Comment by kishor10d** [comment]
Have you checked your .htaccess file? if your homepage is loading, it means project is working correct. You just have to make sure that your .htaccess file performing correct or not.

**Comment by kishor10d** [comment]
@drexvictor : no response, so close the issue
