### ISSUE TITLE
Delete Database

### ISSUE THREAD

**Issue by learningsourc** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#103]
Can i use whitout database ?
i want learn how ci whitout database

**Comment by mckaygerhard** [comment]
@learningsourc  https://github.com/codeigniterpower/codeigniter-login

use the commits history to lear how to use without database.. 

this project Admin-Panel-User-Management-using-CodeIgniter if more for multiuser role and great production focus..

**Comment by kishor10d** [comment]
As above comment seems like answer of this question and the current project is build for database interactions.
Here closing this issue.
