### ISSUE TITLE
status of project

### ISSUE THREAD

**Issue by mckaygerhard** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#104]
hi i liked the project adn becouse also cos use and allow older software coexits with newer ones.. 

i like to know if still continue to support CI3 until ends and more.. cos i already used CI2 and CI3 and i own patched any secirity flan

 respect older CI and older ltdadmin i think if nothing is broken nothing needs to change.. 

about future what about other databases? specially odbc.. (implicts not use of active recordds)

**Comment by kishor10d** [comment]
@mckaygerhard Thanks for the comment.
I will try to maintain this project till support of PHP 8.1 version. Also, currently no plans of providing support for other databases.
Very soon I will convert this project in CodeIgniter 4 or Laravel (separate repository).

**Comment by kishor10d** [comment]
@mckaygerhard - [CIAS using CI4](https://github.com/kishor10d/ci4-admin-panel).
Here is the repository where I started converting the same project in CodeIgniter 4.

**Comment by mckaygerhard** [comment]
> @mckaygerhard Thanks for the comment. I will try to maintain this project till support of PHP 8.1 version.

will be great has this working in modern engines too, i dont have so much interest in fashioned features.. **i was talking about bacguard compatibilty without leave with future one and MAINTENANCE of course of this one**

> Also, currently no plans of providing support for other databases. 

that is pretty not so usefully, mysql is toy db for big companies.. **but its ok.**. 

> Very soon I will convert this project in CodeIgniter 4 or Laravel (separate repository).

as i pointed i dont have interest in CI4 is so complicated.. .. too much MVC .. CI3 and CI" featured a permisive coding

**Comment by kishor10d** [comment]
@mckaygerhard Your point might be valid about continuation of same project with CI3, but there is not support for PHP versions like PHP 8+ for CI-3.
So I am also moving towards CI4, those who are using PHP7.3 still can use this project and do the further development according to the requirement.

**Comment by mckaygerhard** [comment]
@kishor10d  php 8 for CI3 is already addressed https://github.com/pocketarc/codeigniter with https://github.com/bcit-ci/CodeIgniter/pull/6227 and https://github.com/bcit-ci/CodeIgniter/pull/6186 and finally https://github.com/bcit-ci/CodeIgniter/pull/6173
