### ISSUE TITLE
Having lots of error

### ISSUE THREAD

**Issue by shuttercaptured** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#106]
hello I hope you guys are still here. I am currently having many errors on the code hope you can help me. 

![image](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/assets/152072001/e210dee2-eaa3-4753-9458-d3d565e03d12)

**Comment by kishor10d** [comment]
@shuttercaptured This project supports till PHP 7.3 version. The CodeIgniter 3 framework is not supporting the further versions of PHP.
If you install PHP 7.3 or 7.4, it will work for you.

**Comment by mckaygerhard** [comment]
Support for php 8 is partially done https://forum.codeigniter.com/showthread.php?tid=78091&pid=383537#pid383537 but not official supported for codeigniter upstream.. due stupid behaviour.. 

with few changes (maybe more than just few) it runs without security issues! https://github.com/bcit-ci/CodeIgniter/pull/6173

a complete working fork is on codeigniterpowered organization
