### ISSUE TITLE
Make New URL On Admin Panel ?

### ISSUE THREAD

**Issue by aehacker** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#11]
How to create new URL like mydomain.com/http://mydomain.com/admin/userListing ?

i want to connect new PHP page to admin panel like that! (mydomain.com/admin/Connect)!

**Comment by kishor10d** [comment]
You can paste your controllers to subfolder like
```controllers/admin/login```

You can change the route to

```$route["admin/connect"] = "admin/login";```

Then you can fire the url like
http://mydomain.com/admin/connect

**Comment by aehacker** [comment]
No! how you connect "userListing" to users.php ?

**Comment by kishor10d** [comment]
@aehacker : You have to go for codeigniter documentations.

You have to check following files.
1. ```application/config/routes.php```
2. ```application/controllers/users.php```
3. ```application/views/users.php```

Q. How you connect "userListing" to users.php ?
You need to check routes of the application where I created userListing route. After that you have to check the controller called users. In controller, there is a function called userListing, in that function at the end you can see the view filename.

**Comment by aehacker** [comment]
**how i make own myfile.php like that?**

**Comment by kishor10d** [comment]
You need to create your own controller, model and view in the respective folders.
1) Controller - ```controllers/Myfile.php```
2) Model - ```model/Myfile.php```
3) View - ```view/myfile.php```

You need to write the code accordingly. Take help from user controller.
