### ISSUE TITLE
after login "loginMe" controller is not found

### ISSUE THREAD

**Issue by rizwan4317** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#14]
after login loginMe controller is not ..........

**Comment by kishor10d** [comment]
There is no controller named loginMe, the code is in Login.php controller.
Please check your .htaccess settings. Also check that your mod_rewrite.so is not commented.

```#LoadModule rewrite_module modules/mod_rewrite.so```

Remove # from this lines in file httpd.conf from apache config.

**Comment by react-hunter** [comment]
I have done this.
But, not solved problem.
