### ISSUE TITLE
Delete does not work, No style when editing a user.

### ISSUE THREAD

**Issue by LadyNay** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#15]
Hi,

I have thoroughly enjoyed your application. I have found that the Delete button in the userListing does not work, and also when I want to edit the user the text and all is there but the template does not pull through.

could you please have a look at that, also I would love it if you built that Task system on, I am am struggling to find a stand alone application for that.

**Comment by kishor10d** [comment]
@LadyDeathKZN : please check your browser console. You might miss something. There may be some javascript error. If you find that, please put it in next comment.

The task system (menus) which I mentioned over there is just to show the access levels for Roles in the system. If you want the further development on that, gather your requirement, get coding help from the repository and DIY accordingly.

**Comment by LadyNay** [comment]
Thank, you so much for getting back to me!!!

Here is the errors I am getting, and thank you again for the super quick response, I am new to Codeigniter so I am not that clued up, and appreciate your help.

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
demo.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
light-bootstrap-dashboard.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
animate.min.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
pe-icon-7-stroke.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery-1.10.2.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap.min.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap-checkbox-radio-switch.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
chartist.min.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap-notify.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
editUser.js:8 Uncaught ReferenceError: $ is not defined
    at editUser.js:8
light-bootstrap-dashboard.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
demo.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery-1.10.2.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bg-main.jpg Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap.min.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap-checkbox-radio-switch.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
chartist.min.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap-notify.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
light-bootstrap-dashboard.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
demo.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
4:380 Uncaught ReferenceError: $ is not defined
    at 4:380
assets/img/favicon.ico Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap.min.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
animate.min.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
light-bootstrap-dashboard.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
demo.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
pe-icon-7-stroke.css Failed to load resource: the server responded with a status of 500 (Internal Server Error)
util.js:221 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
uB.j @ util.js:221
(anonymous) @ js:134
(anonymous) @ js:53
(anonymous) @ js:50
(anonymous) @ js:53
(anonymous) @ js:105
(anonymous) @ js:50
(anonymous) @ js:105
(anonymous) @ js:50
(anonymous) @ js:105
Tc @ js:52
Sc.ib @ js:105
(anonymous) @ util.js:1
util.js:221 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
uB.j @ util.js:221
(anonymous) @ js:134
(anonymous) @ js:53
(anonymous) @ js:50
(anonymous) @ js:53
(anonymous) @ js:105
(anonymous) @ js:50
(anonymous) @ js:105
(anonymous) @ js:50
(anonymous) @ js:105
Tc @ js:52
Sc.ib @ js:105
(anonymous) @ util.js:1
common.js:49 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
_.sb @ js:35
(anonymous) @ common.js:49
(anonymous) @ common.js:188
c @ common.js:43
(anonymous) @ AuthenticationService.Authenticate?1shttp%3A%2F%2Flocalhost%2Ffarming%2FeditOld%2F4&callback=_xdc_.…:1

All the files are available in the assets file, so I am not sure why they are throwing out errors on this specific page.

**Comment by kishor10d** [comment]
You missed some path of your application. Please check the path on particular page. May be its issue with Google Map and thats why other assets also not loading properly. Please check and update.
