### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by munimaubdullah** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#16]
Fatal error: Call to undefined function password_verify() in D:\xampp\htdocs\code_admin\application\helpers\cias_helper.php on line 46

**Comment by kishor10d** [comment]
Your PHP version might be less than 5.5. the password_verify() function introduced from 5.5 on wards. Please check the [answer on stackoverflow](https://stackoverflow.com/questions/21775970/php-fatal-error-call-to-undefined-function-password-verify)
