### ISSUE TITLE
After login "loginMe" controller is not found : ISSUE On server

### ISSUE THREAD

**Issue by priti321** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#17]
when i run project on localhost it run successfully,
but when upload on server it shows login page,
when enter login details it redirect to loginMe with 404 Not Found.---Plz help

**Comment by eviance** [comment]
Two things impose me:
The first is the routing and configuration setting
the other is .htaccess
I drove the entire catalog for the production and server outside and everything works
any logs in the apache ??

do you use the search function and  read README.md
+1) enable mod_rewrite.dll (or mod_rewrite.so) by removing leading # in httpd.conf.
+2) After that, follow this solution https://stackoverflow.com/questions/24472349/htaccess-doesnt-work-on-xampp-windows-7

**Comment by priti321** [comment]
route.php :
$route['default_controller'] = "login
$route['404_override'] = 'error';
$route['loginMe'] = 'login/loginMe';

i am facing problem only when running on server,on xampp it run properly.

config.php :
$base  = "http://".$_SERVER['HTTP_HOST'];
$base .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);
$config['base_url'] = $base;

.htaccess : 
DirectoryIndex index.php
RewriteEngine on
 
RewriteCond $1 !^(index\.php|(.*)\.swf|forums|images|css|downloads|jquery|js|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ ./index.php?$1 [L,QSA]

**Comment by eviance** [comment]
Try setting as i wrote with httpd.conf.

**Comment by priti321** [comment]
i am new with codeigniter...please tell me path of  httpd.conf file.

**Comment by priti321** [comment]
i have problem only when run on server.
when it run on xampp it run properly.

**Comment by kishor10d** [comment]
@priti321 : httpd.conf file is on your server. If you have access to change it then change it. If you don't have access then contact to your service provider and ask to activate "_mod_rewrite.dll_" or "_mod_rewrite.so_" (linux-server).

**Comment by priti321** [comment]
ok & Thankss.

**Comment by priti321** [comment]
i have not authority to any change on server,can u please give me alternate solution on it.

**Comment by kishor10d** [comment]
if mod_rewrite

**Comment by kishor10d** [comment]
if _mod_rewrite_ not enabled then you can't hide ```index.php``` using ```.htaccess```. In that case, you have to provide ```index.php``` in all urls.

**Comment by priti321** [comment]
here also ?
$config['base_url'] = 'http://192.168.1.200/project/index.php';

**Comment by kishor10d** [comment]
No. Its not like that.
Urls in _redirects_, _form_submits_, _anchor_ tags you need to change.

Check login form submit your. Change it to ```index.php/loginMe```. It will work.

**Comment by priti321** [comment]
i am giving the         
index.php/loginMe 
in view file of login page in form tag ...then it redirect to dashboard with 404 not found.

**Comment by kishor10d** [comment]
Same thing you have to do for ```dashboard``` url and all urls of forms_submits, redirects and achor tags.

**Comment by priti321** [comment]
ok...

**Comment by priti321** [comment]
I have done the change in header file as per u say...but till dashboard is not found.

**Comment by priti321** [comment]
is there changes only in view file?

**Comment by kishor10d** [comment]
Please search through all controllers and views for _redirects_, _anchor_ tags and _form-submits_, and change the urls.

**Comment by priti321** [comment]
ok

**Comment by priti321** [comment]
login controller having function isLoggedIn() in which  have redirect('dashboard');
here also add index.php/dashboard

**Comment by kishor10d** [comment]
Yes, exactly. From last 3-4 comments, I am suggesting the same thing.

**Comment by priti321** [comment]
ok

**Comment by priti321** [comment]
i have done this but getting same error

**Comment by priti321** [comment]
Thank u so much...i'm able to see my project on server.

**Comment by kishor10d** [comment]
@priti321 : Welcome, and thanks for showing interest in the repository. :-)
