### ISSUE TITLE
Fatal error: Call to undefined function password_verify() in E:\Ampps\www\freshers\application\helpers\cias_helper.php on line 46

### ISSUE THREAD

**Issue by bhaskarkv** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#19]
Fatal error: Call to undefined function password_verify() in E:\Ampps\www\freshers\application\helpers\cias_helper.php on line 46

**Comment by kishor10d** [comment]
Which php version are you using?
Can you please check with previous issues.
[Call to undefined function password_verify()](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/issues/1)
