### ISSUE TITLE
Not Found  The requested URL /cias/loginMe was not found on this server.

### ISSUE THREAD

**Issue by tarifrudrapur** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#2]
I have import database file. When i pressing login button it shows this error =>
I am new in CodeIgniter , Help me soon if possible

here is url showing after error
http://localhost/cias/loginMe

Not Found

The requested URL /cias/loginMe was not found on this server.

**Comment by kishor10d** [comment]
Hello, @tarifrudrapur ,
May be you missed ```.htaccess``` file in the project folder. Please find it.

**Comment by kishor10d** [comment]
@tarifrudrapur : I again pushed some changes today, regarding password hashing and user email exist check. So please download the repository again. And try with these new functionalities.

1) Hashed Password.
2) User already exist or not check while creating user.

**Comment by tarifrudrapur** [comment]
@kishor10d 
I just pull your latest changes. I am still getting same error ( not found ) .
.htaccess also there

**Comment by kishor10d** [comment]
@tarifrudrapur : can you tell me your root folder on localhost and how you are using it to navigate the project(url).

**Comment by iHunt101** [comment]
Same here.. The "$route['loginMe'] = 'login/loginMe';" is not define correctly.

**Comment by kishor10d** [comment]
I think the problem with your .htaccess.
Have you configured your database?

**Comment by iHunt101** [comment]
Yes the database is set. Here is the .htaccess.
`DirectoryIndex index.php
RewriteEngine on
 
RewriteCond $1 !^(index\.php|(.*)\.swf|forums|images|css|downloads|jquery|js|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ ./index.php?$1 [L,QSA]`

**Comment by kishor10d** [comment]
Can we connect over any other media like skype?
My skype id is kishor.itg
