### ISSUE TITLE
Update to CodeIgniter4

### ISSUE THREAD

**Issue by ghost** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#20]

**Comment by kishor10d** [comment]
CI4 is under development. I am planning new repository for CI4 once it released in production.

**Comment by kishor10d** [comment]
@You85 : [CIAS updated to CI - v3.1.6](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/commit/d88c2015ba7a59969a573e017e41565afc928390)
