### ISSUE TITLE
reset password

### ISSUE THREAD

**Issue by mohsin8951** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#21]
When i reset password am unable to login again. for admin, manager and employee.
can please fix this issue

**Comment by kishor10d** [comment]
@mohsin8951 : Is that problem at your end. Sorry for late reply, I am busy with some work. If you have same problem persist then please reply.

**Comment by mickaelmonsieur** [comment]
into:
application/views/changePassword.php 
application/views/addNew.php 
application/views/editOld.php

change maxlength to "20".

**Comment by mickaelmonsieur** [comment]
in application/views/addNew.php also...

**Comment by kishor10d** [comment]
@mickaelmonsieur : You can do this at your end, but if you are suggesting change to me then I will do it by now.

[Check the commit](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/commit/229db8e0f4a16aa33285952c01efcd896febdea5)
