### ISSUE TITLE
How do i change username and password for the mysql

### ISSUE THREAD

**Issue by ghost** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#23]
How do i change username and password for the mysql

**Comment by kishor10d** [comment]
@magnus505 : Are you asking for changing of username and password of your mysql server?
Here is the link.
https://stackoverflow.com/questions/20562648/how-to-change-username-and-password-of-mysql.

If you want to know about the current project then here is the code for generating password with password hashing in PHP ;

```password_hash($your_password, PASSWORD_DEFAULT);```

This line will generate hashed password for you, you can copy and paste it in the ```tbl_user```.
