### ISSUE TITLE
How to enable mod_rewrite in Ngnix server

### ISSUE THREAD

**Issue by kalyan6013** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#24]
Hi

I have deployed your code in my nginx server and I was able to access login page and after I try to login it is throwing 404 error. 

I saw your ReadMe file where you mentioned for apache server. But I'm not able to modify the changes in nginx server. I searched in google and got different answers but nothing worked for me. Help me with this.

**Comment by kishor10d** [comment]
@kalyan6013 : Actually nginx not supporting mod_rewrite as it is apache module. You just need to define the rewrite rule as per nginx.
Please refer this link : https://www.nginx.com/blog/converting-apache-to-nginx-rewrite-rules/
