### ISSUE TITLE
If any error in form submit, values are not retaining in the form

### ISSUE THREAD

**Issue by mslabba** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#25]
While submitting a form, if form fields have some error, it will return with a validation error message, but the form doesn't retain the form values.

**Comment by kishor10d** [comment]
@mslabba : I didn't use ```set_value()``` function in form inputs. If you want to implement then you can change it at your end. I will update this thing in next release. Thanks, you gave me space for improvement.
