### ISSUE TITLE
Api feature

### ISSUE THREAD

**Issue by d33pak-s1ngh** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#27]
can you add api based access of functionality in this project. where for login tokens will be generated so it can be used in android also.

**Comment by kishor10d** [comment]
@d33pak-s1ngh : Yes, Actually I am thinking about it. I am thinking to start work on this.

**Comment by nrodriguezm** [comment]
Any updates on this? Thanks!

**Comment by kishor10d** [comment]
@nrodriguezm : Sorry to say, but I didn't work on it.
