### ISSUE TITLE
Getting Error Of baseURL in editUser.js file in assets folder

### ISSUE THREAD

**Issue by Syedwaheed** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#29]
hi @kishor10d,
I m getting an error in editUser.js file in assets folder. The path is in following line:
<script src="<?php echo base_url();?>assets/js/editUser.js" type="text/javascript"></script>.
When i access the Add New user or edit button on user page i m getting an error. Can you please help me to resolve it.Following is the log error image.
![capture](https://user-images.githubusercontent.com/14071753/34719474-cfec8dfc-f55c-11e7-8fa7-baa9b0eaca00.JPG)

**Comment by kishor10d** [comment]
@Syedwaheed : From the screenshot, I come to know that you have error in ```addUser.js```. Please confirm that there is a script in ```header.php``` file.
```
<script type="text/javascript">
    var baseURL = "<?php echo base_url(); ?>";
</script>
```

**Comment by Syedwaheed** [comment]
@kishor10d  Thanks for your prompt reply. Thats is perfect now. But i was wondering that all other pages are working pretty fine except these two. Thanks alot.

**Comment by kishor10d** [comment]
@Syedwaheed : Because, we have script depend on baseURL in addUser.js and editUser.js.
