### ISSUE TITLE
call_user_func_array()

### ISSUE THREAD

**Issue by mvolotov** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#30]
after install you receive the following error:
`call_user_func_array() expects parameter 1 to be a valid callback, class 'Error' does not have a method 'index'`
But method index is in the class Error

Server conf: Ubuntu 16.04 simple LAMP (PHP 7, MySql 5.6)

**Comment by kishor10d** [comment]
@AsteriaGamer : Hello, I done with some changes, can you please pull the new changes and then check. If any error then please update me.

**Comment by mvolotov** [comment]
https://i.imgur.com/m8GGcto.png
Now there is a notification that the page is not found. This is very strange, considering that on OpenServer everything is working fine.

**Comment by mvolotov** [comment]
After reading the documentation, the error was corrected. The file names of models and controllers must start with a capital letter.

**Comment by mvolotov** [comment]
Also, if you use Lighttpd as the web server, then in the settings you should not uncomment mod_rewrite, and add the following line: 
`url.rewrite-if-not-file = ("^/[^?]*(\?.*)?$" => "/index.php$1")`

**Comment by kishor10d** [comment]
@AsteriaGamer : Thanks a lot for using repository.
