### ISSUE TITLE
file upload problem

### ISSUE THREAD

**Issue by d33pak-s1ngh** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#31]
i think you have not updated codeigniter setup properly from 2.2 to 3.1.6 because file upload is not working in the setup please have a look into that i have updated the mime.php in config folder still not working error i am getting is
file type is not allowed when i have define type in config array.

```
$config = array(
                'upload_path' => "./assets/images/profile",
                'allowed_types' => "image/jpg|image/png|image/jpeg",
                'overwrite' => false,
                'max_size' => "1000",
                'remove_spaces' => true
            );
```
here i have define the jpg,png,and jpeg but i cant upload any of image file.

**Comment by kishor10d** [comment]
In the configuration, you just need to define extension, not mime type like ```jpg|png|jpeg|gif|doc``` etc.
```
$config = array(
                'upload_path' => "./assets/images/profile",
                'allowed_types' => "jpg|png|jpeg",
                'overwrite' => false,
                'max_size' => "1000",
                'remove_spaces' => true
            );
```

**Comment by kishor10d** [comment]
@d33pak-s1ngh : Hello, Thanks for the catch. Actually I forget to change the config folder in solution. You saved my life. I made necessary changes and then committed.
Thanks once again.
