### ISSUE TITLE
My modification

### ISSUE THREAD

**Issue by rintoprie** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#32]
Hi @kishor10d I just downloaded your code and did some modification on them. May I upload the modified code to my repository? I will mention your name in the description/Readme page to give the credit. Thanks in advance.

**Comment by kishor10d** [comment]
@rintoprie : Hey, first of all thanks for using the repository. And yes you can modify the code as per your requirement and can push in your fork.
Thanks once again.
