### ISSUE TITLE
Updating the UI with latest ADMIN LTE

### ISSUE THREAD

**Issue by koushikbasu** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#34]
Have you thought of Updating the UI with latest ADMIN LTE, cause the new admin LTE also has few updates.

**Comment by kishor10d** [comment]
@koushikbasu : Hey, I released last version of CIAS today by using AdminLTE 2.1.0.
I will work on latest AdminLTE. I will inform you once done. Keep in touch.

**Comment by kishor10d** [comment]
@koushikbasu : Hello, done with new update (AdminLTE 2.1.0 to 2.4.5). Check once.

Happy coding!
