### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by koushikbasu** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#35]
Does anyone facing the following issue? If yes, please share me the solution asap. Thanks in advance.
A PHP Error was encountered
Severity: Warning

Message: call_user_func_array() expects parameter 1 to be a valid callback, class 'Error' does not have a method 'index'

Filename: core/CodeIgniter.php

Line Number: 532

**Comment by kishor10d** [comment]
@koushikbasu : Please pull the latest master changes. This error will recover. I have missed to update config files in application folder.

**Comment by koushikbasu** [comment]
The latest version is also having same issue on webserver, but working fine on localhost?
Anything else could be reason???

**Comment by developer7007** [comment]
Hi,
I am also facing same issue. can u plz check what is the issue.

**Comment by kishor10d** [comment]
@developer7007 : Hello, The files are renamed and made the controller names start with Capital letter. Please pull again, upload and check.
I tried it on my webserver for PHP5.6 and PHP7.0. It is working great.

**Comment by koushikbasu** [comment]
Yes, I also fixed the issue similarly, it's so silly actually I should've checked that before. And also the models name need to changed with caps.

**Comment by developer7007** [comment]
@kishor10d Thanks for reply. It is working now.
