### ISSUE TITLE
Change edit route

### ISSUE THREAD

**Issue by jappa91** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#36]
Hey,

first of all thanks for sharing this project:) for me its the first time working with mvc and codeigniter. i like your example of your own control where you check for the rights. verry usefull for me.

now i am trying to change the routes to make it set to my backend. now only i cant get the edit user route working. is there something special about this route?

for example add new user or user list i changed to
admin/user/list
admin/user/new

$route['admin/user/list'] = 'user/userListing';
$route['admin/user/list/(:num)'] = "user/userListing/$1";
$route['admin/user/add'] = "user/addNew";

now when i do exaxtly the same with editOld.

$route['admin/users/editOld(:num)'] = "user/editOld/$1";
and when i go do admin/user/edit/2

 it keeps saying page not found.

also a other question shouldnt be the pageNotFound() not be placed in the base control?

**Comment by kishor10d** [comment]
@jappa91 : Hey can you change this line
```$route['admin/users/editOld(:num)'] = "user/editOld/$1";```
to this
```$route['admin/users/editOld(:num)'] = "user/edit/$1";```

Then it will work
