### ISSUE TITLE
forget password/mail not working

### ISSUE THREAD

**Issue by jappa91** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#37]
Hey, sorry to ask something again :)

Maybe do you have any idea why sending emails for forget password is not working.

i started with using my own smtp mail server settings on localhost., i already find out that xampp have no default support for sending mails. so i setup everything to make it work on xampp. but still when i press forget password it says(Email has been failed, try again. ) at this point i thought 2 things or my smtp details are wrong or i i did something wrong with enable sendmail on xampp.

so i tried it with smtp from google on my hosting to see if the problem was just on localhost or my own smtp. but still i get the msg (Email has been failed, try again)

Any idea what it can be?

both own email and gmail are working and i can connect to smtp from my phone.
i setup all details in the constants.php
i tried to enable ssl since my own smtp needs ssl with adding $config['smtp_crypto'] = "ssl"; to the emailConfig function in cias_helper.php

do you have any idea what i do wrong?

**Comment by kishor10d** [comment]
@jappa91 : Hey, I tried a lot on my localhost, but enable to figure out why the SMTP emails are not sent.
On the server, it is running smoothly with ```sendmail``` protocol. I tried all type of things to send email from smtp.

I am thinking of integrating PHPMailer or SwiftMailer for emails (but it is again a dependency).
