### ISSUE TITLE
User can redirect back to dashboard after logout.

### ISSUE THREAD

**Issue by Syedwaheed** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#39]
Hi, 
Thanks for this template. I have changed Email with user name for login and its working fine now. But when i logout i have seen that the user can move back to dashboard with the browser forward and backward button. So i want to restrict the user to move back to dashboard with back and forward button. I have seen your template and its working fine and i think this is happened because of username login. Can you please help me out for this. Thanks in advance.

**Comment by kishor10d** [comment]
@Syedwaheed : I can't understand, what you are trying to ask. Do you have this problem with my code OR you have the problem with your code and you want some help?

**Comment by kishor10d** [comment]
closed because of inactivity.
