### ISSUE TITLE
hi kishor

### ISSUE THREAD

**Issue by janarth20** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#40]
hi bro.
i jst download the admin panel source code.
thanks for it.

Jst wana ask. How do I add sub menu for the side menu?

**Comment by Syedwaheed** [comment]
hi @janarth20 you can use (https://adminlte.io/themes/AdminLTE/index2.html) for your submenu. Thanks

**Comment by janarth20** [comment]
@Syedwaheed hi bro. Thanks for the info. Appreciate it alot

**Comment by Syedwaheed** [comment]
@janarth20 no problem i was doing the same and there was no one to tell me about this. Suddenly i came across the template. Glad to hear that you find it.

**Comment by janarth20** [comment]
@Syedwaheed  thanks bro.
One more thing would like to ask. Hope u dont mind.
About validation in adding new user.
Msg "Email alredy taken" Actually how does it works?
Can u explain me if possible

**Comment by kishor10d** [comment]
@janarth20 : Code is here in the model ```application/models/User_model.php```.

```
function checkEmailExists($email, $userId = 0)
    {
        $this->db->select("email");
        $this->db->from("tbl_users");
        $this->db->where("email", $email);   
        $this->db->where("isDeleted", 0);
        if($userId != 0){
            $this->db->where("userId !=", $userId);
        }
        $query = $this->db->get();
        return $query->result();
    }
```

This code checks that the email is already exists in database or not. Once the record found, it returns ```Email already taken```.

**Comment by janarth20** [comment]
Actually my browser cache prob. Now settle. Anyway thanks bro
