### ISSUE TITLE
How to give same styling as dashboard to new views that i am creating

### ISSUE THREAD

**Issue by savyad** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#42]
Actually i have created some new views but i want to know how i can give them exact same styling as other and where i can manage them i can't find their css files please help me with that

**Comment by kishor10d** [comment]
@savyad : Hey, we have ```header.php``` and ```footer.php``` files in ```views/includes/``` folder. So the layout of already set.
If you want to create view with same style then just follow ```views/dashboard.php``` file.

Code Hint:
```
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        <i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard
        <small>Control panel</small>
      </h1>
    </section>
    
    <section class="content">

    <!-- Your HTML here --->

    </section>
</div>
```
