### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by rajansarkar** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#43]
**Call to undefined method Admin::isLoggedIn()**
Admin is controller name. login after this message.

**Comment by blueocean879** [comment]
Hey, I am getting error when trying to run this site on linux.
Can we run this site on linux successfully?

**Comment by kishor10d** [comment]
@rajansarkar : The method is exists in the file here : https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/blob/master/application/libraries/BaseController.php

Please check. Also there is no Admin class in the repository.

**Comment by kishor10d** [comment]
@blueocean879 : Yes you can run this site on linux because I developed it on linux itself (I have Ubuntu).
In case any error, please update the comment with error you got.
