### ISSUE TITLE
LoginMe not found on this server

### ISSUE THREAD

**Issue by savyad** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#44]
Even after following your solution in readme  the problem is not resolved.It is perfectly working when it is on godaddy,when i moved it on aws ec2 it's not working.

**Comment by savyad** [comment]
I solved it

**Comment by react-hunter** [comment]
Hi Savyad,
How did you solve it ?
I can't find the way to solve this...

**Comment by react-hunter** [comment]
I have tried this on local - xampp environment.

**Comment by savyad** [comment]
just follow the instructions properly
