### ISSUE TITLE
Forgot password mail ok, but link redirect to login

### ISSUE THREAD

**Issue by janschroeven** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#45]
Hi,

I configured your app, which is great, but i cannot get the forgot password to work.
If go to forgot password, i correctly get the email with the link, but everytilme i get redirected to the login page.

The token and email in the link are correct, i veriefied them in the database, so 
$is_correct = $this->login_model->checkActivationDetails($email, $activation_id); should return 1.
But for some reason it does not.

Could you please help?

Thanks!

**Comment by janschroeven** [comment]
Hi,

I found the issue. In the Login_model.php for method checkActivationDetails($email, $activation_id) there was `return $query->num_rows;` which should be `return $query->num_rows();`

**Comment by kishor10d** [comment]
@janschroeven : Hi, thanks for such silly mistake I have done. I just resolved this bug in new commit. Thanks once again.

**Comment by janschroeven** [comment]
@kishor10d  no problem, easy to overlook some brackets :)
