### ISSUE TITLE
How can I use CRUDigniter in your project?

### ISSUE THREAD

**Issue by Mckalashnik** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#46]
Thanks for code. Site is working, no issues.

Please, help my (( Please create a new video on how to use [CRUDigniter](http://www.crudigniter.com/) in your project. It does not succeed.

**Comment by kishor10d** [comment]
@Mckalashnik : You can directly use CRUDIgniter for next modules if you want, just you have to keep eye on routes and design.
