### ISSUE TITLE
How to implement datatables

### ISSUE THREAD

**Issue by mkshravan** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#48]
I would like to add datatables, please let me know, how to add it. Because when I am adding datatables then after clicking below links of datatables then 404 error occured.

**Comment by kishor10d** [comment]
@mkshravan : I think you want search, sort, pagination facility of datatables. I already done with this in Codeigniter server side pagination. But if you still want to use then you just have to write the query without limit and pass it to datatables. It will work with pagination.

**General use of datatables** : List, Paging, Searching, Sorting (client side) on whole dataset.
If you want datasets on demand then you need have to formulate Datatables using server-side pagination.
