### ISSUE TITLE
Sidebar Not working

### ISSUE THREAD

**Issue by savyad** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#49]
sidebar toggle button not working it's not collapsing(on Desktop) and for mobile it's already collapsed.

**Comment by kishor10d** [comment]
@savyad : I think you didn't pull repository completely. I tried it so may times on my Desktop & Mobile, its working good.
According to sidebar settings, whenever page refreshed on Desktop; sidebar open by default.
Whereas, page refreshed on Mobile; sidebar collapsed by default.
