### ISSUE TITLE
localhost/cias does not work

### ISSUE THREAD

**Issue by imranitian** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#5]
500 internal error is shown. please help

**Comment by phil8001** [comment]
Test my solution

htaccess file:

`#DirectoryIndex index.php
RewriteEngine on
RewriteBase /
RewriteCond $1 !^(index\.php|(.*)\.swf|forums|images|css|downloads|jquery|js|robots\.txt|favicon\.ico)
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ ./index.php?$1 [L,QSA]`

works fine for me!
