### ISSUE TITLE
EditUser not working, Need Different Dashboard for different manager and users and also need more than one super admin

### ISSUE THREAD

**Issue by binayak87** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#55]
Hi I need more than one super admin
Also Edit User from super admin panel not working. Clicking submit button does not do anything

and lastly,
different dashboard from different manager and users groups. Like dashboard1 will be visible to manager1 and user1, user2, user3 and dashboard2 will be visible to manager2 and user4, user5, user6.

Thanks,

**Comment by kishor10d** [comment]
@binayak87 : I just check by cloning repository. Edit user is perfectly working.

This is starter (boilerplate) for admin panel. You can pull the repository and you are free to change as per your requirements. You can do customization as per your need.

But for suggestion, big thanks from my side!

**Comment by kishor10d** [comment]
I will start working by next week on roles & responsibilities.
Also I will create the hierarchy of user by role.
