### ISSUE TITLE
GroceryCrud integration

### ISSUE THREAD

**Issue by mnabarro** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#59]
Hello!. I'm trying to use your CIAS project as start for a web application where most of action is CRUD over several tables.

I'm not getting GC working, I guess there's something bad with css files. 
Could you guide me to integrate GC or, even better, post an example. I think it would be a valuable extra for this project.

Best regards!.

**Comment by eviance** [comment]
725/5000
Hello

GC uses its formatting theme, installing or copying folders you create in w / assets / grocery_crud / themes. And here, as you will notice for this type of table generation, they use ready-made templates. They are also paid and based on the bootstrap.

I understand that you are not dealing with CSS but there is all the formatting that sometimes bites with the Admin Panel version. Conditional formatting in GC modules.

I think that you should start with modifying skins / creations here.

With copying, for example, like me from the Admin Panel CSS - but remember, you must know the minimum - integration is not required. Depends on the construction of your main panel.

PS. remember adding such chapters, for example, charts also bite with the Admin Panel

Greetings.

**Comment by kishor10d** [comment]
@mnabarro : Actually GC works on jQueryUI. May be some of bootstrap classes are overriding the css and it wont work. I will check at my end to implement GC.

**Comment by kishor10d** [comment]
@mnabarro : As GroceryCrud is almost stopped their development after CI v2.x. We dropped the idea of integrating it in the current project.
