### ISSUE TITLE
Admin login not workin

### ISSUE THREAD

**Issue by spencershaw** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#6]
admin@codeinsect.com
codeinsect

NOT WORKING ON ONLINE DEMO. THEY ARE ON LOCALHOST THOUGH

**Comment by kishor10d** [comment]
I provided admin credentials, from the day one! So many people gone through this demo, and change the passwords so many times.
Every time I changed the password. I don't know why someone doing this.
