### ISSUE TITLE
treeview / treeview-menu is not working in a sidebar?

### ISSUE THREAD

**Issue by phpthinky** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#60]
Hello I download it last january the sidebar toggle/dropdown menu is working, but as i see you update the application i download it again the see the changes, i like your new update, but i can;t make the sidebar dropwdown treeview/treeview menu to work see my code below.

```
<li class="treeview">
              <a href="#" >
                <i class="fa fa-file-o"></i>
                <span>Post</span><span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="<?=base_url('post/add')?>"><i class="fa fa-circle-o"></i>Add</a></li>
                <li><a href="<?=base_url('post')?>"><i class="fa fa-circle-o"></i>View all</a></li>
              </ul>
            </li>
```

No error in my console.

**Comment by phpthinky** [comment]
I update my code a bit now it working but not the same as i expected it to work. Hope someone who encounter this may help you.

```
<li class="treeview">
              <a href="<?=base_url('post')?>" > /* add the post index directly to parent menu */
                <i class="fa fa-file-o"></i>
                <span>Post</span><span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="<?=base_url('post/add')?>"><i class="fa fa-circle-o"></i>Add</a></li>
            /*    <li><a href="<?=base_url('post')?>"><i class="fa fa-circle-o"></i>View all</a></li> */ /* i remove this line */
              </ul>
 </li>

```

**Comment by kishor10d** [comment]
@coloftech : Hi, will check and come with the update. Meanwhile you can try new html and css classes from AdminLTE latest version. I think the html you have written is not supported by new version of AdminLTE.

**Comment by boedyirh** [comment]
Experience the same thing....no dropdown menu in the sidebar

**Comment by phpthinky** [comment]
> @coloftech : Hi, will check and come with the update. Meanwhile you can try new html and css classes from AdminLTE latest version. I think the html you have written is not supported by new version of AdminLTE.

Nope, I am using the adminlte2, for now i copy all your code to work with the default adminlte2 theme.

**Comment by kishor10d** [comment]
@coloftech and @boedyirh : Done with this thing. Please check this [commit](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/commit/d93a53d9be3d6d63872c046d9f6e5fe10b5a7a9f)

```data-widget="tree"``` only this thing was missing to work multilevel menus.
