### ISSUE TITLE
Codeigniter 3.1.10 Update

### ISSUE THREAD

**Issue by boedyirh** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#61]
I can see, that your Code Igniter is 3.1.6,
It is now Codeigniter 3.1.10. 
In case it doesnot break the code. I think it would be good idea to update Codeigniter.

**Comment by kishor10d** [comment]
@boedyirh : Sure, I will try for this.

**Comment by kishor10d** [comment]
@boedyirh : I have upgraded the migrated system from v 3.1.6 to v 3.1.10. Do check, and thank for suggestion.
Thanks for using repository. :100:
