### ISSUE TITLE
User Privileges?

### ISSUE THREAD

**Issue by junaiddarjat** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#64]
On features, it's mentioned:

"Predefined Roles (You can change roles and rights as per your project requirement)."

How abouts does one would do this then?

I'm looking at the following project which credits you:
https://github.com/pars11/Codeigniter-User-Panel-Management

There seems to be user privileges / authorization per page, such as Admin can access all, Manager can access 'addNewTask' and User can just view 'etasks', but whereabouts is this even done at?! I can't figure it out for the life of me. All I see is that 'sessions' library is being used but that dint turn me to any leads either..

Any or all help is appreciated.

**Comment by kishor10d** [comment]
Please find ```header.php```, there I applied condition to show/hide options.

Please find ```application/library/BaseController.php```, there I assign no access page.
