### ISSUE TITLE
Functions for deleting and modifying unusable data

### ISSUE THREAD

**Issue by frederichidan** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#66]
Hello,

I used your application to develop my application around your development and code.

Except that I have a real problem, when I code as I usually do in order to be able to delete a data in a MySQL database or modify it, I systematically have an error and it complicates my task a little.

On the other hand when I try to adapt your code to my needs I also have another error because you don't really delete but you update the data so that it is no longer visible. 

Can you give me an orientation to get around this difficulty, please?

**Comment by kishor10d** [comment]
@frederichidan : Hi, sorry for delayed response. Can you elaborate, or update question with the sample code? I am unable to understand what you are asking for.
