### ISSUE TITLE
forgot password is not working

### ISSUE THREAD

**Issue by sangeeram** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#68]
hi when i give email in forgt password block it is showing "email sent is failed". pls clear this doubt .

**Comment by kishor10d** [comment]
@sangeeram : It will work when you actually host your project on some host. Or if you have proper settings for SMTP, then you can configure them from `application/config/constants.php` file.

**Comment by arora-sakshi** [comment]
I have changed smtp settings in application/config/constants.php but still getting the same issue

**Comment by arora-sakshi** [comment]
> @sangeeram : It will work when you actually host your project on some host. Or if you have proper settings for SMTP, then you can configure them from `application/config/constants.php` file.

This is not working on hosting. Can you please look into this issue ?

**Comment by diazAP** [comment]
how to configure smtp services sir?
and what is the function of ci_sessions table?

im new to this

btw thank you for creating this project

**Comment by kishor10d** [comment]
@arora-sakshi & @diazAP : 
With CodeIgniter, there are some issues with SMTP. Can you please setup mails using "sendmail". It works like charm. Code is working for some hosting providers but others are not working with it.

**Comment by kishor10d** [comment]
@diazAP : ci_sessions table is just a provisional table. If you want to manage your sessions (store session ids) in database, then you can utilize that table. It is provided by CodeIgniter.

Reference Link: https://codeigniter.com/user_guide/libraries/sessions.html#database-driver

**Comment by diazAP** [comment]
> @diazAP : ci_sessions table is just a provisional table. If you want to manage your sessions (store session ids) in database, then you can utilize that table. It is provided by CodeIgniter.
> 
> Reference Link: https://codeigniter.com/user_guide/libraries/sessions.html#database-driver

okay, thank you sir

**Comment by arora-sakshi** [comment]
> sendmail

Thank you @kishor10d 

I am getting following error after login in admin:

**idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated** 

Can you please look into this?

**Comment by kishor10d** [comment]
@arora-sakshi : It look like your intl extension is not configured properly. Please check and enable from php extensions.
