### ISSUE TITLE
Main Navigation Items

### ISSUE THREAD

**Issue by spencershaw** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#7]
On the Main Navigation Menu on the left hand side, there are a number of items that seem to do nothing:
 New Task
 My Tasks
 Task Status
 Task Uploads
 Reports

**Comment by lloricode** [comment]
maybe its just a demo, the sample code is really matter

**Comment by kishor10d** [comment]
@spencershaw : Its a demo. When you login with different users (admin, manager, user), you can show hide the navigation menus. Also if you hit those urls manually, still it will show the error that you are not allowed to visit this url. Thanks @lloricode
