### ISSUE TITLE
HTML spanish chars UTF-8 encoding problems(á,é,í,ñ)

### ISSUE THREAD

**Issue by Rainwod-cloud** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#77]
Hi again, recently i see this problem in this case in any of my views title or body page:
![imagen](https://user-images.githubusercontent.com/67616159/86194923-08583e00-bb50-11ea-923d-899b047eb92c.png)
in my controller is defined as:
![imagen](https://user-images.githubusercontent.com/67616159/86194988-3473bf00-bb50-11ea-8f63-21dd89f0284f.png)
and in the view of the controller method:
![imagen](https://user-images.githubusercontent.com/67616159/86195094-7270e300-bb50-11ea-89fc-ca10704c3dec.png)
This is only happen using BaseController `loadViews()` function, please some help!!
**PD:** i have correctly defined all parameters of encoding in my php.ini, database conecction is under UTF-8 and the header file contain `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`  inside the `<head>`tags

**Comment by kishor10d** [comment]
@Rainwod-cloud : Hello, I tried random Spanish word in the code. And it is working fine. Its too from ```loadViews()```.
Check the screenshots.

**Title Bar Code:**

![inside code](https://user-images.githubusercontent.com/5403520/86271364-60dc1980-bbea-11ea-938a-159f6b9cc6b1.png)

**Output:** Please check green coloured boxes.

![utf8-characters](https://user-images.githubusercontent.com/5403520/86271394-6cc7db80-bbea-11ea-859e-9f17d30d9a30.png)


I have on only this code in ```<head>``` section. ```<meta charset="utf-8">```

**Comment by Rainwod-cloud** [comment]
Thank you very much, my error, my IDE, was deconfigured and saved the files in a different encoding than utf-8 greetings and sorry for the inconvenience
