### ISSUE TITLE
User name not translates to UTF-8

### ISSUE THREAD

**Issue by kzolee1** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#82]
I have checked the config, it is UTF-8, the database is utf8_unicode_ci. When i create a user or modify a user with non-latin charactes (like ó) the database value changes to ??

Especially, when a user name starts with Tó

**Comment by kishor10d** [comment]
@kzolee1 : Can you please check the collation of your name field? Please check the screenshot. For name field we have utf8_general_ci, what is in your case?

![utf](https://user-images.githubusercontent.com/5403520/104729006-c98d7c80-575d-11eb-9fdb-f08edf71e37e.PNG)
![unicode](https://user-images.githubusercontent.com/5403520/104729199-1a9d7080-575e-11eb-9765-ddf8938d1f1e.PNG)

**Comment by kzolee1** [comment]
Collation is set to Table default. (Database: 10.4.12-MariaDB, server: PHP 7.4.14 Development Server)
If i set the name field to utf8_general_ci the problem remains.

**Comment by kishor10d** [comment]
@kzolee1 : The issue is neither of CodeIgniter nor of the repository. It is the collation issue with your MySQL version. Hence closed.
