### ISSUE TITLE
Can`t Make new user

### ISSUE THREAD

**Issue by finnie2006** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#83]
When i click submit button nothing happens 

ixed Content: The page at 'https://MYDOMAIN/addNew' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://MYDOMAIN/checkEmailExists'. This request has been blocked; the content must be served over HTTPS.
send @ jquery.min.js:2

**Comment by finnie2006** [comment]
With http i can

**Comment by kishor10d** [comment]
Please check your base_url in `application/config/config.php` file.

**Comment by finnie2006** [comment]
wich line

**Comment by finnie2006** [comment]
FOund it,
