### ISSUE TITLE
Self Registration

### ISSUE THREAD

**Issue by Ivan367al** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#84]
Hello,
I've done the registration page in my website and I use password_hash for the password, but the system doesn't recognise the password.
Not being able to find where you hash the password adding a new user, I can't solve this problem.
Any advice?
Thanks
  Ivano

**Comment by kishor10d** [comment]
@Ivan367al : Hashing password function and verification methods are written in helper.
Please check file on this path: `application/helpers/cias_helper.php`

**Comment by kishor10d** [comment]
@Ivan367al : no response, hence closed.
