### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by GetItBac92** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#85]
hello, I am trying to modifying the code in such way that a user can register himself in the system.. I have made a link just after forgot password and created a corresponding method in the controller class..however it is showing me the following error:
Message: call_user_func_array() expects parameter 1 to be a valid callback, class 'Error' does not have a method 'index'

Filename: core/CodeIgniter.php

Line Number: 532

Backtrace:

File: C:\xampp\htdocs\DUSPORTS2\DUSPORTS\DUSPORTS\index.php
Line: 315
Function: require_once

**Comment by kishor10d** [comment]
@GetItBac92 : May be you issue with your urls. Your project folder is not on the root, my be that is the reason of the problem.
Please keep updating your issue.

**Comment by kishor10d** [comment]
@GetItBac92 : no response, Hence closed.
