### ISSUE TITLE
Admin-Control-

### ISSUE THREAD

**Issue by GetItBac92** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#86]
ISSUE # 1 : After login "loginMe" controller is not found :

Lot of people raising this issue, I resolved it 4-5 times for every user. People are not searching for closed issues. Thats why I am going to put this here.

How to get over this issue?

1) enable mod_rewrite.dll (or mod_rewrite.so) by removing leading # in httpd.conf. 2) After that, follow this solution https://stackoverflow.com/questions/24472349/htaccess-doesnt-work-on-xampp-windows-7

ISSUE # 2 🤐  Call to undefined function password_verify() :

Solution is here 🤥  Call to undefined function password_verify()

**Comment by kishor10d** [comment]
@GetItBac92 : I am not getting why you posted the content of README.md file here.

Do you have same issues? The solution is provided on the given links. You have to follow that.

Your PHP version must be greater than or equal to PHP 5.5 (PHP >= PHP 5.5). This thing is mentioned under Version Information in README.md
