### ISSUE TITLE
Need Special Calling for User

### ISSUE THREAD

**Issue by 3vluzi** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#87]
Hi, thanks for your amazing work.
I am new to CI, and I want to know more about How to call any simple function for example:
Call who is login aka display username who is currently login and the level of that user.
and then place it anywhere.

In my project i want to create attendance system that call userlogin to be recorded on db.

thanks.

**Comment by 3vluzi** [comment]
Oh, i`ve  tried and this work

//On my_helper.php

function sedanglogin()
{
    $pdo = &get_instance();
    $pdo->load->library('session');
    $sesiNYA = $pdo->session;
    return $sesiNYA;
}

////anywhere
$loggedin = sedanglogin();
   
      foreach ($loggedin as $s) {
        $useridnya = $s['userId'];
        $rolenya = $s['role'];
        $roleteksnya = $s['roleText'];
        $namanya = $s['name'];
        $loginterakhir = $s['lastLogin'];
}

//echo $namanya and so on

**Comment by kishor10d** [comment]
@3vluzi : If you have special requirements then please do not create issues. We can connect in other ways.

**Comment by 3vluzi** [comment]
oh ok sir. sorry for that, i am new to git
