### ISSUE TITLE
so many columns are missing in table ..please update database sql file

### ISSUE THREAD

**Issue by spiritgulshan** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#88]

**Comment by kishor10d** [comment]
@spiritgulshan : Hi. Please do not clone the master branch of repository.
Please dowbload the lastest release here. https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/releases/tag/1.4

**Comment by rmogro** [comment]
> @spiritgulshan : Hi. Please do not clone the master branch of repository. Please dowbload the lastest release here. https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/releases/tag/1.4

The database file is not modified, could you be so kind as to upload an update
