### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by rockbansal** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#89]
Error Number: 1054

Unknown column 'BaseTbl.isAdmin' in 'field list'

SELECT `BaseTbl`.`userId`, `BaseTbl`.`password`, `BaseTbl`.`name`, `BaseTbl`.`roleId`, `BaseTbl`.`isAdmin`, `Roles`.`role` FROM `tbl_users` as `BaseTbl` JOIN `tbl_roles` as `Roles` ON `Roles`.`roleId` = `BaseTbl`.`roleId` WHERE `BaseTbl`.`email` = 'admin@example.com' AND `BaseTbl`.`isDeleted` = 0

Filename: C:/xampp/htdocs/Admin-Panel-User-Management-using-CodeIgniter-master/Admin-Panel-User-Management-using-CodeIgniter-master/Admin-Panel-User-Management-using-CodeIgniter-master/system/database/DB_driver.php

Line Number: 691

**Comment by kishor10d** [comment]
@rockbansal : Sorry for the late reply. Please download the released version. Don't download the master branch.
Link: [Latest Release](https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/releases/tag/1.4)
