### ISSUE TITLE
CodeIgniter Upgrade? 

### ISSUE THREAD

**Issue by prassaschr** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#9]
Hi.
How can I upgrade Codeigniter to the latest version?
Thank you

**Comment by kishor10d** [comment]
You can follow the link https://www.codeigniter.com/userguide3/installation/upgrade_300.html
Which is the major upgrade from 2.2.x to 3.0.x. Major changes are here only.

What about CI4? => It is yet to release, after release, I will initialize new repository for that.
