### ISSUE TITLE
Database schema is out of date

### ISSUE THREAD

**Issue by ghost** [kishor10d/Admin-Panel-User-Management-using-CodeIgniter#93]
The database on repository is very old. It doesn't reflect current changes to the system. 

Can you please upload the new version.

Unknown column 'BaseTbl.isAdmin' in 'field list'

SELECT `BaseTbl`.`userId`, `BaseTbl`.`password`, `BaseTbl`.`name`, `BaseTbl`.`roleId`, `BaseTbl`.`isAdmin`, `Roles`.`role` FROM `tbl_users` as `BaseTbl` JOIN `tbl_roles` as `Roles` ON `Roles`.`roleId` = `BaseTbl`.`roleId` WHERE `BaseTbl`.`email` = 'admin@example.com' AND `BaseTbl`.`isDeleted` = 0

Column "isAdmin" doesn't exist on cias.sql on the repo

**Comment by kishor10d** [comment]
@kolorete78 : The database is updated now. You can pull the latest changes. Although, some work is pending regarding the roles and rights. Very soon will update full working demo.
